### ISSUE TITLE
Hiring Cost Calculation

### ISSUE THREAD

**Issue by turtle11235** [turtle11235/capital-clicker#20]
Hiring cost is incorrect when the user doesn't have enough money to hire and the root is full. Has to do with the way HireOne is calculated. Need to stop relying on canHire as a proxy for isFull

**Comment by cpartington** [comment]
Current line of thinking: HireOne should be the cost of the cheapest employee to hire. It's calculated based on canHire, which checks two things:
1. There needs to be enough space to hire a new employee
2. There needs to be enough money

canHire can be false even when there's space available. The possible result is that HireOne thinks that a manager needs to be hired and falsely reports a higher number.

**Comment by cpartington** [comment]
Using "canHire" was definitely one of the issues. I created a method to iterate over the full tree rather than checking one set of employees and the cost. The same issue showed up in the EmployeeManager.hire() method (although I think this function needs to be completely rewritten). Looks like something is still broken though.
